### ISSUE TITLE
更新去除fangle/timeline下广告

### ISSUE THREAD

**Issue by primovist** [yichahucha/surge#10]
优化
http-response ^https?:\/\/(api|mapi)\.weibo\.(cn|com)\/2\/((groups|statuses\/friends|fangle)\/timeline|(profile\/)?statuses(\/unread|extend|\/positives\/get)?|comments\/build_comments|photo\/recommend_list|stories\/(video_stream|home_list)|service\/picfeed) requires-body=1,max-size=-1,script-path=省略
内容添加

const path12 = "/fangle/timeline";

if (url.indexOf(path12) != -1) {
    filter_timeline();
}

**Comment by primovist** [comment]
所有的转义符都不见了😂

**Comment by yichahucha** [comment]
这是哪个页面的

**Comment by primovist** [comment]
底下菜单栏-消息-通知-各种已经关注的超话和新鲜事的详情。

**Comment by yichahucha** [comment]
更新了 试试
