### ISSUE TITLE
脚本失效了，京东显示无价格信息淘宝商品详情页打不开

### ISSUE THREAD

**Issue by chan1108** [yichahucha/surge#101]
如题

**Comment by HelperInCa** [comment]
jd tb 都无价格信息

**Comment by no5no6** [comment]
看了下请求： https://price.icharle.com/?product_id=https://item.m.jd.com/product/100015451127.html  这个获取历史价格的接口 报 504 了，应该是历史价格服务出了问题。

**Comment by liqixjcn** [comment]
确实失效了
