### ISSUE TITLE
Netflix评分失效了吗

### ISSUE THREAD

**Issue by Yixuling** [yichahucha/surge#113]
ios.prod.ftl.netflix.com mitm失败了

**Comment by Jay17642121508** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yichahucha** [comment]
fix

**Comment by Yixuling** [comment]
> fix
![c4846701e34225779273aeba97f45a5](https://user-images.githubusercontent.com/29663375/217201695-533a6455-5f7e-40d0-b6f5-a7bdb4d06db0.jpg)
在登陆账号的时候，mitm 失败，账号也等不上呢。不知道是什么原因。

**Comment by Jay17642121508** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
