### ISSUE TITLE
微博去广告建议

### ISSUE THREAD

**Issue by primovist** [yichahucha/surge#12]
建议添加正则匹配

https://api.weibo.cn/2/statuses/video_timeline

建议修改

const path15 = "/statuses/video_timeline";

if (
    url.indexOf(path1) != -1 ||
    url.indexOf(path2) != -1 ||
    url.indexOf(path10) != -1 ||
    url.indexOf(path15) != -1 
) {
    let obj = JSON.parse(body);
   

function filter_timeline_statuses(statuses) {
    if (statuses && statuses.length > 0) {
        let i = statuses.length;
        while (i--) {
            let element = statuses[i];
            if (is_timeline_likerecommend(element.title)) statuses.splice(i, 1);
            /*if (is_timeline_ad(element.promotion)) statuses.splice(i, 1);
            */
            if (is_timeline_ad(element.mblogtype)) statuses.splice(i, 1);
        }
    }
    return statuses;
}

function is_timeline_ad(mblogtype) {
    return mblogtype && mblogtype && mblogtype == 1 ? true : false;
}

/*
function is_timeline_ad(promotion) {
    return promotion && promotion.type && promotion.type == "ad" ? true : false;
}
*/

**Comment by yichahucha** [comment]
这是哪个页面的
