### ISSUE TITLE
京东获取不到商品信息，昨天还好用

### ISSUE THREAD

**Issue by Xadyy** [yichahucha/surge#21]
查询了Surge的最近请求提示:
04:51:52.498124 Rule evaluating requires DNS lookup for rule: RULE-SET NeteaseMusic.list
04:51:52.555984 Sub-rule matched: DOMAIN-SUFFIX jd.com
04:51:52.556096 Rule matched: RULE-SET China.list
04:51:52.556325 Reuse previous connection: #639
04:51:52.556697 HTTP response script found: https://raw.githubusercontent.com/yichahucha/surge/master/jd_price.js
04:51:52.647912 Script failed, abort.
04:51:52.648295 Disconnect with reason: Closed by remote (Script abort)

**Comment by androidcn** [comment]
正常使用吗?

**Comment by zmqcherish** [comment]
Disconnect with reason: Closed by remote (Script abort)
这个错误解决了吗？quanx的没问题，surge会报错
