### ISSUE TITLE
淘宝历史价格查询

### ISSUE THREAD

**Issue by Wangsc1** [yichahucha/surge#23]
大佬，历史价格的查询界面能适配支持黑暗模式么，淘宝tf已经黑暗模式了

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by yichahucha** [comment]
页面都是淘宝的，淘宝适配就有

**Comment by cainiao2223** [comment]
大佬每次点击商品显示有点慢，是因为在加载价格数据吗

**Comment by yichahucha** [comment]
> 大佬每次点击商品显示有点慢，是因为在加载价格数据吗

1.屏蔽了IP 使用域名请求肯定没IP直接请求快
2.另外还要加载历史价格数据，都会导致慢
