### ISSUE TITLE
taobao price

### ISSUE THREAD

**Issue by ee-5** [yichahucha/surge#25]
Quantumultx依据readme配置完成后，无法出现“服务—历史价格”
   配置不变，卸载重装淘宝app后，成功。

  20min之后重新测试，依旧失败

**Comment by yichahucha** [comment]
文档添加了点注释，仔细按照文档再配置下

**Comment by Nergrove** [comment]
> 文档添加了点注释，仔细按照文档再配置下

我也是同样的问题，卸载重装淘宝之后当时能用，然后如果打开其他app又切回来以后，就没有用了。

**Comment by yichahucha** [comment]
规则发出来看看

**Comment by Nergrove** [comment]
> 规则发出来看看

配置就是按照你的文档中的配置，而且我自己也试过调整过很多错。规则用的是神机的，没啥特殊的。

**Comment by Nergrove** [comment]
> 规则发出来看看

配置就是按照你的文档中的配置，而且我自己也试过调整过很多次。规则用的是神机的，没啥特殊的。

**Comment by yichahucha** [comment]
telegram：is0x1

**Comment by yichahucha** [comment]
抓包找找看是哪个 IP 没有 reject，导致脚本不触发

**Comment by yichahucha** [comment]
新增了一条规则，加上这个试试
`ip-cidr, 106.11.162.0/24, reject, no-resolve`

**Comment by ee-5** [comment]
已添加三条规则。
1⃣️卸载重装淘宝后，进宝贝页面有卡顿，生效，网络活动reject多为203.119.175.0/24。
2⃣️不登陆账号，隔一小时左右测试一次，均生效。
3⃣️登陆账号后，生效。
4⃣️登陆账号二十分钟后测试，登陆宝贝页面流畅，不生效，reject多为203.119.144.0/23。

**Comment by yichahucha** [comment]
文档更新了 再试试😂

**Comment by ee-5** [comment]
使用脚本不生效，使用规则屏蔽ip完美生效，感谢y大！
