### ISSUE TITLE
[功能请求] jd_price quan x

### ISSUE THREAD

**Issue by ytzong** [yichahucha/surge#31]
症状：由于慢慢买的数据返回较慢，会经常导致 JD 界面卡屏

建议：可否做一个精简版，不再显示在商品界面，而是异步请求数据，通过 push 通知的方式只弹出历史最低价格

谢谢

**Comment by yichahucha** [comment]
[tb_price_lite.js](https://raw.githubusercontent.com/yichahucha/surge/master/tb_price_lite.js)
[jd_price_lite.js](https://raw.githubusercontent.com/yichahucha/surge/master/jd_price_lite.js)

**Comment by ytzong** [comment]
太赞了，感谢大佬
