### ISSUE TITLE
surge ios钉钉打卡脚本问题

### ISSUE THREAD

**Issue by jeizas** [yichahucha/surge#33]
ios系统：13.3.1
surge版本：4.0.2
钉钉版本：8.9
问题：添加了钉钉打卡提醒的脚本，到时间没反应，如图脚本
![image](https://user-images.githubusercontent.com/12405225/75250068-798a8c00-5812-11ea-99bd-67d0e64a12da.png)

**Comment by yichahucha** [comment]
先设置成每秒执行一次，看看是否执行脚本
