### ISSUE TITLE
钉钉clock_in.js

### ISSUE THREAD

**Issue by JEGNUI** [yichahucha/surge#38]
老哥，关于钉钉签到脚本想求解几个问题

1、如果我选择提醒其他软件的话，是否只是替换掉第十三行钉钉的网页链接就行呢？

2、还选择check in/out 是根据系统时间还是根据脚本执行链接呢？

**Comment by yichahucha** [comment]
dingtalk://dingtalkclient/page/link?url=https://attend.dingtalk.com/attend/index.html

1.只替换链接进行
2.取的是系统时间

**Comment by JEGNUI** [comment]
好的，非常感谢
