### ISSUE TITLE
去京东开屏广告 可兼容价格插件

### ISSUE THREAD

**Issue by codexss** [yichahucha/surge#56]
`^https?:\/\/api\.m\.jd.com\/client\.action\?functionId=start`
```
var obj = JSON.parse($response.body)
delete obj.images
$done({body: JSON.stringify(obj)})
```

**Comment by vhvg** [comment]
在包含 ^https?:\/\/api\.m\.jd.com\/client\.action\?functionId=start 的rule-set中，若将使用的规则选为REJECT-TINYGIF，确实可以兼顾去京东开屏广告与历史价格script，若为REJECT，则会很快失效。

我猜想上述方法与本issue的解决方法类似。

**Comment by yichahucha** [comment]
> 在包含 ^https?://api.m.jd.com/client.action?functionId=start 的rule-set中，若将使用的规则选为REJECT-TINYGIF，确实可以兼顾去京东开屏广告与历史价格script，若为REJECT，则会很快失效。
> 
> 我猜想上述方法与本issue的解决方法类似。

建议采用这种方法

**Comment by freedomandcourage** [comment]
it wokes like a charm
