### ISSUE TITLE
Netflix rating Surge无效

### ISSUE THREAD

**Issue by z4jst** [yichahucha/surge#57]
你好，ios使用surge，开启了 mitm，使用模块导入，进入netflix 后，没有评分出现，想问问是哪里出现了问题吗？
(京东历史价格模块正常)
![B3770F52-903C-41BB-ABB3-75AFC89003FF](https://user-images.githubusercontent.com/15144170/81140199-1c8e1d80-8f9b-11ea-946e-90e58515dc65.png)

**Comment by yichahucha** [comment]
脚本应该没问题 没订阅模块具体不太清楚
