### ISSUE TITLE
淘宝和京东比价问题。

### ISSUE THREAD

**Issue by z306334796** [yichahucha/surge#64]
这两个脚本都会在详情页面卡顿一下，淘宝的时间更长，甚至会卡掉Quan X的VPN，然后经常提示网络崩溃。希望能够修复一下。

**Comment by babylife** [comment]
小火箭有一样的问题

**Comment by yichahucha** [comment]
因为要请求比价数据 卡顿无法避免 用最新的脚本会快些

**Comment by wjsmt** [comment]
淘宝一直不生效 重装也不行 不知道为什么

**Comment by Jay17642121508** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
