### ISSUE TITLE
JD 9.0.8 比价工作不正常

### ISSUE THREAD

**Issue by KleinerSource** [yichahucha/surge#66]
开启调试模式 能够正常显示比价
关掉调试模式后 比价不显示.
查询日志 发现  开启调试模式后 访问 会正常出现 client.action?functionId=wareBusiness 并成功被重写

但是关闭调试模式后 查询日志 只会出现 client.action? 然后就没有了 反复开关客户端 和QC 偶尔能遇到一次 client.action?functionId=wareBusiness

**Comment by yichahucha** [comment]
^https?://api\.m\.jd\.com/client\.action\?functionId=(wareBusiness|serverConfig|basicConfig)

换这个正则 然后更新下脚本
