### ISSUE TITLE
淘宝比价会导致一些宝贝链接打不开 等久了网络崩溃提醒，药品类的就会出现这种情况

### ISSUE THREAD

**Issue by lycorisxv** [yichahucha/surge#68]
![image](https://user-images.githubusercontent.com/62493587/90854410-75998a00-e3af-11ea-8a97-8153a9866e23.png)

**Comment by forest-river** [comment]
习惯就好

**Comment by babylife** [comment]
发现淘宝经常要卸载重装，不知道有什么办法

**Comment by yichahucha** [comment]
我试了下正常 用最新脚本
