### ISSUE TITLE
比价脚本失效了

### ISSUE THREAD

**Issue by howecheung** [yichahucha/surge#71]
<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Removable** [comment]
同样失效，希望大佬能尽快更新~谢谢

**Comment by chenyz1984** [comment]
京东比价和淘宝比价貌似都失效了，商品页面无法加载。

**Comment by Mirasc** [comment]
跪求大佬更新

**Comment by Mirasc** [comment]
好像是  QuanX  的问题   我用Loon还有效 @Removable @chenyz1984 @howecheung

**Comment by iFallen** [comment]
jd可以 ，taobao不行，卸载重装也不显示。大佬什么时候更新啊

**Comment by Gretycos** [comment]
tb的失效了，内置和通知都不起作用
