### ISSUE TITLE
淘宝比价不能用了吗？

### ISSUE THREAD

**Issue by realCD** [yichahucha/surge#74]
同样的设置方法，jd就可以显示历史价格，但是tb不行，是脚本失效了还是我的设置方法不对。
我看README关于QuantumultX中tb的设置有一行小字，即打开淘宝前要先运行脚本，请问，这要怎么操作，我失败的关键难道就在于这句话？

**Comment by Mirasc** [comment]
loon可以用   QuanX  的问题

**Comment by zlq** [comment]
我这里loon也不能用，重装淘宝也不行，京东的可以

**Comment by ardayan** [comment]
我的可以用 卸载淘宝重装 每次打开淘宝要先开qx

**Comment by realCD** [comment]
卸载过了，我的QuantumultX是24小时开着的，没特殊情况就不会关闭。
2020年11月13日 +0800 01:36 ardayan <notifications@github.com>，写道：

**Comment by realCD** [comment]
原来淘宝的历史价格查询在保障里面，我一直以为跟京东一样呢。
![image](https://user-images.githubusercontent.com/47968720/99159863-b3425080-271b-11eb-84d2-bd8d6e8bf7d0.jpeg)

**Comment by shuigeupup** [comment]
价格在保障里面
