### ISSUE TITLE
wb_ad部分失效

### ISSUE THREAD

**Issue by vndi** [yichahucha/surge#75]
使用后依然出现微博信息流广告

**Comment by yichahucha** [comment]
具体一点 那个页面

**Comment by vndi** [comment]
> 具体一点 那个页面

信息流主页以“最新微博”排序时在开启去广告脚本和MitM后依然出现广告
![Uploading IMG_2909.png…]()

**Comment by vndi** [comment]
![IMG_2909](https://user-images.githubusercontent.com/42428427/101563706-bcfe6180-3a04-11eb-991e-9b25e3662d90.png)

**Comment by yichahucha** [comment]
刷了一会 没发现
试试进wb前就把脚本开好 或者 按照文档再配置一下确保脚本生效

**Comment by vndi** [comment]
> 刷了一会 没发现
> 试试进wb前就把脚本开好 或者 按照文档再配置一下确保脚本生效

重新添加后成功解决问题，感谢您拨冗
