### ISSUE TITLE
小火箭使用京东比价脚本的问题

### ISSUE THREAD

**Issue by babylife** [yichahucha/surge#76]
1. 当使用全局代理的时候，十分正常
2. 当使用配置的时候，只有的CN IP设置为代理的时候，才可以正常获取比价结果，否则 不行
3. 当使用全局代理正常之后，切换其他代理模式，京东也是正常，但是京东退出之后再次进入就不行
4. 尝试日志分析，发现非正常的时候 ，没有manmanmai的网站请求

**Comment by babylife** [comment]
大佬，昨天说到京东小飞机用比价脚本，只能全局代理才可以正常显示的问题，我今日测试下来 发现把101.124.19.122/32 这个加到proxy策略 可以解决问题。原因未知，貌似只能用机场访问这个ip就可以显示比价结果了，没有发现dns查询记录，十分诡异 懒人配置加上这个ip规则目前使用京东比价十分稳定，也不需要全局代理了.
深入发现访问这个IP返回结果比较慢的情况下，可以让脚本正常加载使用，一旦直连就会不生效。 lite版本的京东比价在小火箭上没有问题

**Comment by msn1983aa** [comment]
> 1. 当使用全局代理的时候，十分正常
> 2. 当使用配置的时候，只有的CN IP设置为代理的时候，才可以正常获取比价结果，否则 不行
> 3. 当使用全局代理正常之后，切换其他代理模式，京东也是正常，但是京东退出之后再次进入就不行
> 4. 尝试日志分析，发现非正常的时候 ，没有manmanmai的网站请求

请问您能提供下小火箭怎么写的规则在这里贴出来一下吗？我直接用surge的，测试运行会报错

**Comment by babylife** [comment]
> > 1. 当使用全局代理的时候，十分正常
> > 2. 当使用配置的时候，只有的CN IP设置为代理的时候，才可以正常获取比价结果，否则 不行
> > 3. 当使用全局代理正常之后，切换其他代理模式，京东也是正常，但是京东退出之后再次进入就不行
> > 4. 尝试日志分析，发现非正常的时候 ，没有manmanmai的网站请求
> 
> 请问您能提供下小火箭怎么写的规则在这里贴出来一下吗？我直接用surge的，测试运行会报错

暂时不折腾了，有时间再学习研究下

**Comment by z11119** [comment]
请问pandaVPN怎么购买

**Comment by yichahucha** [comment]
# 不生效或失效的检查一下配置有没有这两条复写，删除试试
# ^https?:\/\/api\.m\.jd.com\/client\.action\?functionId=start - reject
# ^https?:\/\/api\.m\.jd.com\/client\.action\?functionId=(start|queryMaterialAdverts) - reject

没有🚀 再不行卸载重装试试
