### ISSUE TITLE
京东比价失效了

### ISSUE THREAD

**Issue by longgediyi999** [yichahucha/surge#83]

**Comment by Vepoe** [comment]
刚刚我的京东和淘宝的比价都失效了

**Comment by askiter** [comment]
我这边也发现有这个情况，最新商店版本App，有的时候能出来比价的内容，有的时候又出不来，很奇怪

**Comment by Incognito-S** [comment]
同问，试了好多次了，都不行

**Comment by askiter** [comment]
就我目前的测试，发现 京东比价对于 functionId=basicConfig 的时候，能发现比价脚本执行，但是商品页出不来那个比价的信息
但是functionId=wareBusiness的时候比价信息是正常的
今天早上我在家里看到的都是functionId=basicConfig，都出不来比价信息，
但是下午在公司抓到的都是 functionId=wareBusiness，比价信息显示正常

希望大佬能修复一下，谢谢

**Comment by crabmessage** [comment]
京东我这边正常，但是淘宝一直没生效，重装了也一样 @yichahucha

**Comment by ashurinn** [comment]
qx用户且用了神机规则的，请自行在本地添加一条复写：
^https?://api\.m\.jd\.com/client\.action\?functionId=start url reject-200
失效与脚本无关，而是因为规则有冲突，详细看看readme。

**Comment by ashurinn** [comment]
不知道为什么在回复区里正则的反斜杠都自动消失了，自己把正则里的点用反斜杠转义一下试试。

**Comment by burst3166** [comment]
@ashurinn 谢谢，可以了

**Comment by Vepoe** [comment]
> 不知道为什么在回复区里正则的反斜杠都自动消失了，自己把正则里的点用反斜杠转义一下试试。 ^https?://api\.m\.jd\.com/client\.action\?functionId=start url reject-200
> […](#)
> On 10 May 2021, 09:19 +0800, burst3166 ***@***.***>, wrote: @ashurinn 试了你的方法，在最新的京东上，依然无法显示比价信息 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢，是神机那两条去广告的规则导致的，删除已经好了。

**Comment by huaxin233** [comment]
显示 请升级最新版本，历史价将于近期停止老版本维护，请问要怎么做？

**Comment by cryingmyth** [comment]
> 显示 请升级最新版本，历史价将于近期停止老版本维护，请问要怎么做？

我也如此显示，是版本问题吗

**Comment by huaxin233** [comment]
京东是最新版本

**Comment by huaxin233** [comment]
昨天还能用的，记得是前几天更新的京东，今天就不行了

**Comment by Vepoe** [comment]
淘宝和京东都提示了让升级，而且也没见更新啊

**Comment by longgediyi999** [comment]
慢慢买接口升级了和作者无关    web端新增了token并且开了防爬虫   有点难搞    就算作者找到手机端接口   也不免继续被封掉   凉凉

**Comment by yichahucha** [comment]
#87

**Comment by yichahucha** [comment]
脚本使用的比价接口加了 token 验证，不能用了，没有找到合适的比价接口之前，先禁用脚本吧

**Comment by gitehabu** [comment]
禁用：

订阅重写链接后面添加#out=price.js就行啦

**Comment by yichahucha** [comment]
#87
