### ISSUE TITLE
比价更新版本了么，提示更新新版本

### ISSUE THREAD

**Issue by lthero16** [yichahucha/surge#87]

**Comment by xulcdev** [comment]
同问

**Comment by cwwcn** [comment]
同问

**Comment by Sramsh** [comment]
对啊提示老版本不在维护要求升级新版本

**Comment by jqbk** [comment]
同问，京东和淘宝都是

**Comment by kaaaaai** [comment]
同问

**Comment by XiaoGuYa** [comment]
现在脚本调用的API变成了收费模式

**Comment by zjplab** [comment]
同问

**Comment by yichahucha** [comment]
慢慢买的比价接口加了 token 验证，没法用了

**Comment by yichahucha** [comment]
脚本使用的比价接口加了 token 验证，不能用了，没有找到合适的比价接口之前，先禁用脚本吧

**Comment by yichahucha** [comment]
jd_price.js 更新了 可以试试

**Comment by johnnyvipcn** [comment]
jd_price 等大大更新taobao

**Comment by yichahucha** [comment]
tb_price.js 也好了
通知版本暂时无法用

**Comment by icheto** [comment]
您好 我在quan-x上 tb_price.js 似乎还是不能用 提示更新 是地址有变动吗？还是别的原因呢。

**Comment by yichahucha** [comment]
更新下脚本 如果还不行卸载重装

**Comment by siusiu7** [comment]
> 更新下脚本 如果还不行卸载重装

大佬 淘宝的普通商品没问题了 比价也正常，就是天猫商品的页面都打不开 是什么问题

**Comment by yichahucha** [comment]
> > 更新下脚本 如果还不行卸载重装
> 
> 大佬 淘宝的普通商品没问题了 比价也正常，就是天猫商品的页面都打不开 是什么问题

可以打开 更新脚本再试试

**Comment by AronX** [comment]
为什么我的比价更新后永远当前价是最低价，明明不是

**Comment by zhangxuanyu2019** [comment]
我的淘宝比价历史记录只有5月20号开始，之前的都显示没收录有
