### ISSUE TITLE
比价脚本准确性问题

### ISSUE THREAD

**Issue by gogorush** [yichahucha/surge#89]
你好 

比价脚本这次替换了接口之后好像给出的价格并不正确（不是最低价格），能确定下是啥问题吗？

**Comment by mrdear** [comment]
应该是接口问题，这种接口免费的不多，大家再找找好用的接口吧

**Comment by littleanzi** [comment]
大佬，淘宝更新了最新版本比价脚本无效了，淘宝已经卸载重装过两次

**Comment by FrancisNGG** [comment]
> 你好
> 
> 比价脚本这次替换了接口之后好像给出的价格并不正确（不是最低价格），能确定下是啥问题吗？


> 应该是接口问题，这种接口免费的不多，大家再找找好用的接口吧

我还以为是我设置出了问题，原来是换接口了，原来的慢慢买挺准的，现在换了个比价狗，显示都不准确

**Comment by ocean521** [comment]
可以众筹比价接口费用吗，感觉之前的很准，现在的就不说了

**Comment by zongai** [comment]
https://github.com/PPsteven/manmanbuy_js_crack

**Comment by yichahucha** [comment]
换了个接口 试试
