### ISSUE TITLE
希望添加 *.im.weibo.cn

### ISSUE THREAD

**Issue by hello1983** [yichahucha/surge#9]
^https?://(im).weibo.(cn|com)/2(/groups/timeline|/statuses/unread|/statuses/extend|/comments/build_comments|/photo/recommend_list|/stories/video_stream|/statuses/positives/get|/stories/home_list|/profile/statuses|/statuses/friends/timeline|/service/picfeed)

**Comment by yichahucha** [comment]
这个域名是干什么的

**Comment by hello1983** [comment]
微博广告好像是

yel <notifications@github.com>于2019年7月15日 周一下午2:53写道：

**Comment by yichahucha** [comment]
那个页面的广告 能具体点么

**Comment by hello1983** [comment]
开屏广告

yel <notifications@github.com>于2019年7月15日 周一下午2:55写道：

**Comment by yichahucha** [comment]
去开屏广告用的是这个js wb_launch.js
