### ISSUE TITLE
jd_price.js 失效，但 jd_price_lite.js 仍可用

### ISSUE THREAD

**Issue by PatZhuang** [yichahucha/surge#91]
QuanX

jd_price.js 在原本显示历史价格的位置显示「暂无价格信息」，更新脚本、卸载重装 app 无效

但 lite 脚本弹出的通知可以正常获取历史价格信息

**Comment by StimeKe** [comment]
@PatZhuang 可以用这个 https://service.2ti.st/QuanX/Rewrite/jd_tb_price.conf

**Comment by Gretycos** [comment]
这个的jd可以，但是tb不行> @PatZhuang 可以用这个 https://service.2ti.st/QuanX/Rewrite/jd_tb_price.conf

**Comment by StimeKe** [comment]
> 这个的jd可以，但是tb不行> @PatZhuang 可以用这个 https://service.2ti.st/QuanX/Rewrite/jd_tb_price.conf

淘宝需要重装才行，关闭插件打开一次就失效

**Comment by Gretycos** [comment]
> > 这个的jd可以，但是tb不行> @PatZhuang 可以用这个 https://service.2ti.st/QuanX/Rewrite/jd_tb_price.conf
> 
> 淘宝需要重装才行，关闭插件打开一次就失效

重装了也不行，tb用的最新版

**Comment by ciring** [comment]
> > > 这个的jd可以，但是tb不行> @PatZhuang 可以用这个 https://service.2ti.st/QuanX/Rewrite/jd_tb_price.conf
> > 
> > 
> > 淘宝需要重装才行，关闭插件打开一次就失效
> 
> 重装了也不行，tb用的最新版

点开保障信息能看到

**Comment by XieL1989** [comment]
> @PatZhuang 可以用这个 https://service.2ti.st/QuanX/Rewrite/jd_tb_price.conf

失效了？

**Comment by XieL1989** [comment]
失效了大佬，有更新嘛

**Comment by ocean521** [comment]
貌似更新后就失效了

**Comment by Gretycos** [comment]
jd和tb一起双双失效了。。

**Comment by luotiandong** [comment]
> jd和tb一起双双失效了。。

#94  jd 已经提交更新，还没合入。可以尝试使用。

**Comment by GN006** [comment]
> > jd和tb一起双双失效了。。
> 
> #94 jd 已经提交更新，还没合入。可以尝试使用。

jd已可以使用感谢大佬，大佬能修复tb吗

**Comment by yichahucha** [comment]
jd tb已修复
