### ISSUE TITLE
微博启动广告脚本更新

### ISSUE THREAD

**Issue by IvorkChan** [yichahucha/surge#96]
近来发现偶尔失效，抓包看了下似乎需要添加：
lastAdShow_delay_display_time = 0

修改脚本后暂时没发现开屏广告。

**Comment by IvorkChan** [comment]
更新：还是有开屏广告……所以是脚本失效了？

**Comment by yuhangrao** [comment]
同，微博开屏广告失效了

**Comment by hno3yy** [comment]
微博开屏失效了
