### ISSUE TITLE
jd_price.js失效

### ISSUE THREAD

**Issue by myloverhxx** [yichahucha/surge#99]
京东 10.4.3
Shadowrocket 
下午手贱更新了app后，jd_price.js 在原本显示历史价格的位置显示「暂无价格信息」。

**Comment by myloverhxx** [comment]
tb_price.js 只有重新安装app后，第一次可以成功展示比价信息。淘宝 iOSv10.9.0

**Comment by LevineWoo** [comment]
> tb_price.js 只有重新安装app后，第一次可以成功展示比价信息。淘宝 iOSv10.9.0

啊这。。那京东比价呢？我试过重装app京东比价也是一样显示「暂无价格信息」
